import { ROBOT_HAND_SEGMENTS, ROBOT_PALM_DIRECTIONS, type Vec3 } from '../../src/robohand-types';

const add=(a:Vec3,b:Vec3):Vec3=>({x:a.x+b.x,y:a.y+b.y,z:a.z+b.z});
const sub=(a:Vec3,b:Vec3):Vec3=>({x:a.x-b.x,y:a.y-b.y,z:a.z-b.z});
const mul=(p:Vec3,k:number):Vec3=>({x:p.x*k,y:p.y*k,z:p.z*k});
const norm=(p:Vec3)=>Math.hypot(p.x,p.y,p.z);
const unit=(p:Vec3)=>mul(p,1/Math.max(norm(p),1e-8));

/** Independent analytic fixture, not generated by the production IK.
 * Unequal source/robot proportions deliberately expose direction-copy failure.
 * These are synthetic kinematic samples, not measured camera accuracy data.
 */
export function precisionHand(fingers:number[]=[], openness=0, variant=0):Vec3[]{
  const points:Vec3[]=Array.from({length:21},()=>({x:0,y:0,z:0}));
  for(let f=0;f<5;f++){
    const s=ROBOT_HAND_SEGMENTS[f*4], d=unit(ROBOT_PALM_DIRECTIONS[s.finger]);
    const base={x:d.x*s.length*(1.15+variant*.05),y:d.y*s.length*.85,z:d.z*s.length};
    points[f*4+1]=base;
    const lengths=ROBOT_HAND_SEGMENTS.slice(f*4+1,f*4+4).map(s=>s.length*(f===0?1.18:1.04));
    const open=add(base,mul(unit({x:f===0?.8:0,y:1,z:0}),lengths.reduce((a,b)=>a+b,0)));
    if(!fingers.includes(f)){
      let p=base;for(let k=0;k<3;k++){p=add(p,mul(unit(sub(open,base)),lengths[k]));points[f*4+k+2]=p;}
      continue;
    }
    const close={x:.02+variant*.025,y:.72+variant*.015,z:-.43};
    const target=add(mul(close,1-openness),mul(open,openness));
    // Last phalange faces toward the contact from above; thumb faces from below.
    const lastDir=f===0?unit({x:-.35,y:.7,z:-.3}):unit({x:0,y:-.7,z:-.7});
    const p2=sub(target,mul(lastDir,lengths[2]));
    const delta=sub(p2,base), dist=norm(delta), u=unit(delta);
    const along=(lengths[0]**2-lengths[1]**2+dist**2)/(2*dist);
    const height=Math.sqrt(Math.max(0,lengths[0]**2-along**2));
    const pole={x:0,y:1,z:0}, dot=pole.x*u.x+pole.y*u.y+pole.z*u.z;
    const perpendicular=unit(sub(pole,mul(u,dot)));
    points[f*4+2]=add(add(base,mul(u,along)),mul(perpendicular,height));
    points[f*4+3]=p2;points[f*4+4]=target;
  }
  return points;
}

export function precisionFrame(points:Vec3[],at=0,mirror=false,yaw=0){
  const worldLandmarks=points.map(p=>{
    const x=p.x*Math.cos(yaw)+p.z*Math.sin(yaw),z=-p.x*Math.sin(yaw)+p.z*Math.cos(yaw);
    return {x:mirror?x:-x,y:-p.y,z};
  });
  return {worldLandmarks,landmarks:worldLandmarks.map(p=>({x:.5+p.x*.18,y:.7+p.y*.18,z:p.z*.18})),
    handedness:mirror?'Left':'Right',handednessScore:1,capturedAt:at,receivedAt:at};
}

export function precisionFist():Vec3[]{
  const points=precisionHand();
  for(let f=0;f<5;f++)for(let k=0;k<3;k++){
    const angle=f===0?.45+k*.65:1.15+k*1.2;
    const direction=f===0?unit({x:-.5,y:Math.cos(angle),z:-Math.sin(angle)}):{x:0,y:Math.cos(angle),z:-Math.sin(angle)};
    points[f*4+k+2]=add(points[f*4+k+1],mul(direction,ROBOT_HAND_SEGMENTS[f*4+k+1].length*1.04));
  }
  return points;
}
