import {test} from 'node:test';
import assert from 'node:assert/strict';
import {decodeLite,liteBgr,chooseDriveDetector} from '../../src/drive/lite-detector';
import {fitAnchorProfile,parseAnchorProfile,estimateAnchorRange,type RangeAnchor} from '../../src/drive/anchor-range';
import {MobileBudget} from '../../src/drive/mobile-budget';
import {MeterCoverage} from '../../src/drive/meter-coverage';
import {VehicleTracker,type DriveTrack} from '../../src/drive/tracking';
const box={label:'car',score:.99,x0:.43,x1:.57,y0:.4,y1:.65};
// Explicit synthetic truth, never a real camera profile: 1/Z = .1*y-.03.
const points:RangeAnchor[]=[...[[.25,.55],[.75,.55],[.25,.65],[.75,.65],[.25,.8],[.75,.8]].map(([x,y])=>({u:x*1280,v:y*720,zM:1/(.1*y-.03),split:'fit' as const})),
  ...[[.4,.6],[.6,.7]].map(([x,y])=>({u:x*1280,v:y*720,zM:1/(.1*y-.03),split:'check' as const}))];
const profile=()=>fitAnchorProfile(1280,720,1,points);
test('Nano initial mobile hint is selectable, not an acceptance verdict',()=>{assert.equal(chooseDriveDetector('auto',true),'lite');assert.equal(chooseDriveDetector('auto',false),'rtdetr');assert.equal(chooseDriveDetector('rtdetr',true),'rtdetr');});
test('Nano consumes BGR raw bytes, not normalized RGB',()=>{const rgba=new Uint8ClampedArray(416*416*4);rgba.set([11,22,33,255]);const out=liteBgr(rgba);assert.equal(out[0],33);assert.equal(out[416*416],22);assert.equal(out[2*416*416],11);assert.throws(()=>liteBgr(new Uint8ClampedArray(4)));});
function output(cls=2,score=.9){const data=new Float32Array(3549*85);const row=26*52+26,at=row*85;data.set([0,0,Math.log(80/8),Math.log(80/8),1],at);data[at+5+cls]=score;return {data,at};}
test('Nano decodes raw grid/exp sizes and removes top-left padding',()=>{const {data}=output();const [b]=decodeLite(data,[1,3549,85],832,416);assert.equal(b.label,'car');assert.ok(Math.abs(b.x0-168/416)<1e-6);assert.ok(Math.abs(b.y0-168/208)<1e-6);assert.throws(()=>decodeLite(data,[1,3549,84],832,416));});
test('Nano class winner excludes signs, global NMS suppresses duplicate vehicles',()=>{const {data,at}=output(11,.98);data[at+7]=.9;assert.deepEqual(decodeLite(data,[1,3549,85],416,416),[]);const other=output();other.data.set(other.data.slice(other.at,other.at+85),other.at+85);other.data[other.at+85]= -1;assert.equal(decodeLite(other.data,[1,3549,85],416,416).length,1);other.data[other.at+2]=Infinity;assert.equal(decodeLite(other.data,[1,3549,85],416,416).length,1);});
test('Anchor fit independently checks known metre scale, domain and ordinal direction',()=>{const p=profile();assert.ok(p.checkMaxM<1e-8);assert.ok(Math.abs(estimateAnchorRange(box,p,1280,720,1).distanceM!-1/.035)<1e-6);const nearer=estimateAnchorRange({...box,y1:.75},p,1280,720,1);assert.ok(nearer.distanceM!<estimateAnchorRange(box,p,1280,720,1).distanceM!);assert.equal(nearer.provenance,'ground-anchor-geometry');assert.equal(nearer.intervalCalibrated,false);});
test('Anchor import ignores forged coefficients and rechecks original measured references',()=>{const p=profile();assert.deepEqual(parseAnchorProfile({...p,coefficients:[0,0,999],checkMAEM:-100}),p);const bad=structuredClone(p);bad.points[6].zM=60;assert.throws(()=>parseAnchorProfile(bad),/kiểm/);});
test('Anchor calibration fails closed for missing/rank/span/duplicate references',()=>{assert.throws(()=>fitAnchorProfile(1280,720,1,points.slice(0,6)),/6 mốc/);assert.throws(()=>fitAnchorProfile(1280,720,1,points.map(p=>({...p,v:400}))),/cùng điểm|cùng hàng/);assert.throws(()=>fitAnchorProfile(1280,720,1,points.map(p=>({...p,zM:10}))),/8 m/);assert.throws(()=>fitAnchorProfile(1280,720,1,[...points,points[0]]),/cùng điểm/);});
test('Anchor ranging rejects mismatched crop, clipped/small/off-domain vehicles',()=>{const p=profile();for(const b of [{...box,x0:0},{...box,y1:.99},{...box,y0:.64},{...box,x0:.05,x1:.15},{...box,y0:.2,y1:.35}])assert.equal(estimateAnchorRange(b,p,1280,720,1).distanceM,null);assert.equal(estimateAnchorRange(box,p,1280,720,2).distanceM,null);assert.equal(estimateAnchorRange(box,p,720,1280,1).distanceM,null);});
test('Anchor tracker publishes on detector capture and expires at unchanged 1200ms',()=>{const tracker=new VehicleTracker(),range=estimateAnchorRange(box,profile(),1280,720,1);tracker.observe([box],0,100,null,1280,720,new Map([[box,range]]),true,100);assert.ok(tracker.snapshot(0,100).some(t=>t.range.distanceM!==null));assert.ok(tracker.snapshot(0,1201).every(t=>t.range.distanceM===null));});
test('Mobile budget needs 10 measured samples and uses rolling P95, not UA',()=>{const b=new MobileBudget();for(let i=0;i<9;i++)b.observe(100);assert.equal(b.report().state,'probing');b.observe(450);assert.equal(b.report().state,'too-slow');b.reset();for(let i=0;i<10;i++)b.observe(90);assert.equal(b.report().state,'within-budget');b.observe(NaN);assert.equal(b.report().count,10);});
test('Target coverage counts blank boxes, unique captured anchors and no physical acceptance',()=>{const c=new MeterCoverage(),track={id:1,box,ageMs:0,range:estimateAnchorRange(box,profile(),1280,720,1),rangeAgeMs:0} as DriveTrack;c.measurement(0,[track]);c.presentation(0,[track]);c.presentation(100,[track]);c.measurement(100,[{...track,rangeAgeMs:100}]);const blank={...track,range:{...track.range,distanceM:null}};c.presentation(200,[blank]);c.presentation(1200,[blank]);const r=c.report();assert.equal(r.targets[0].freshObservations,1);assert.equal(r.targets[0].boxVisibleMs,1200);assert.equal(r.targets[0].metresVisibleMs,200);assert.equal(r.targets[0].maxBlackoutMs,1000);assert.equal(r.independentMetricAccuracy,null);assert.equal(r.productVerdict,'not-validated');c.reset();assert.equal(c.report().targets.length,0);});
test('Bounded target report discloses truncation instead of claiming complete coverage',()=>{const c=new MeterCoverage();c.presentation(0,Array.from({length:300},(_,i)=>({id:i,range:{distanceM:null}} as DriveTrack)));assert.equal(c.report().targets.length,256);assert.equal(c.report().coverageTruncated,true);assert.equal(c.report().omittedRowVisits,44);c.reset();assert.equal(c.report().coverageTruncated,false);});
